//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmaPlus.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FarmaPlusEntities : DbContext
    {
        public FarmaPlusEntities()
            : base("name=FarmaPlusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblGospodarstvo> tblGospodarstvo { get; set; }
        public virtual DbSet<tblGovedo> tblGovedo { get; set; }
        public virtual DbSet<tblPosjednik> tblPosjednik { get; set; }
        public virtual DbSet<tblUsrPsw> tblUsrPsw { get; set; }
        public virtual DbSet<tblVrstaZivotinje> tblVrstaZivotinje { get; set; }
        public virtual DbSet<tblZivotinja> tblZivotinja { get; set; }
        public virtual DbSet<tblZupanija> tblZupanija { get; set; }
    }
}
