//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmaPlus.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblGovedo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblGovedo()
        {
            this.tblZivotinja = new HashSet<tblZivotinja>();
        }
        
        public int GovedoID { get; set; }
        public Nullable<int> PosjednikID { get; set; }
        public Nullable<int> VrstaZivotinjeID { get; set; }
        [Display(Name = "Ime Životinje")]
        public string Ime { get; set; }
        [Display(Name = "Datum Roðenja")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DatumRodenja { get; set; }
        public string dat { get; set; }
        public string Spol { get; set; }
        public string Pasmina { get; set; }
        public string MajkaKodDrzave { get; set; }
        public string MajkaZivotniBroj { get; set; }
        public string MajkaIme { get; set; }
        public string OtacKodDrzave { get; set; }
        public string OtacHbBroj { get; set; }
        public string OtacIme { get; set; }
        [Display(Name = "Datum upisa u registar ")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> DatumUpisaURegistar { get; set; }
        public string Napomena { get; set; }
        public Nullable<bool> Aktivno { get; set; }
    
        public virtual tblPosjednik tblPosjednik { get; set; }
        public virtual tblVrstaZivotinje tblVrstaZivotinje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblZivotinja> tblZivotinja { get; set; }
    }
}
