//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmaPlus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGospodarstvo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblGospodarstvo()
        {
            this.tblPosjednik = new HashSet<tblPosjednik>();
        }
    
        public int GospodarstvoID { get; set; }
        public string JIBG { get; set; }
        public string Naziv { get; set; }
        public string Ulica { get; set; }
        public Nullable<short> KucniBroj { get; set; }
        public Nullable<int> PostanskiBroj { get; set; }
        public Nullable<int> ZupanijaID { get; set; }
    
        public virtual tblZupanija tblZupanija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPosjednik> tblPosjednik { get; set; }
    }
}
