//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmaPlus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPosjednik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPosjednik()
        {
            this.tblGovedo = new HashSet<tblGovedo>();
            this.tblUsrPsw = new HashSet<tblUsrPsw>();
            this.tblZivotinja = new HashSet<tblZivotinja>();
        }
    
        public int PosjednikID { get; set; }
        public Nullable<int> GospodarstvoID { get; set; }
        public string Email { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Telefon { get; set; }
    
        public virtual tblGospodarstvo tblGospodarstvo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGovedo> tblGovedo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUsrPsw> tblUsrPsw { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblZivotinja> tblZivotinja { get; set; }
    }
}
