//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmaPlus.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblZivotinja
    {
        public int ZivotinjaID { get; set; }
        public int PosjednikID { get; set; }
        public int VrstaZivotinjeID { get; set; }
        [Display(Name = "Broj Životinje")]
        public string OznakaUsneMarkice { get; set; }
        public Nullable<System.DateTime> DatumUvoza { get; set; }
        public Nullable<int> GovedoID { get; set; }
        public Nullable<int> KonjID { get; set; }
        public Nullable<int> SvinjaID { get; set; }
        public Nullable<int> OvcaID { get; set; }
        public Nullable<int> KozaID { get; set; }
        public Nullable<int> MagaracID { get; set; }
        public Nullable<int> NojID { get; set; }
        public Nullable<bool> Aktivna { get; set; }
    
        public virtual tblGovedo tblGovedo { get; set; }
        public virtual tblPosjednik tblPosjednik { get; set; }
        public virtual tblVrstaZivotinje tblVrstaZivotinje { get; set; }
    }
}
